source_list:
  - SB
  - OL
  - CP
  - ADDR

target_list:
  - REGIS_DIM
  - CHILD_DIM

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data
  filename: receipts_delta_GBR_14_10_2017.csv

CP:
  s3_conf:
    s3_bucket: aws-rdd-bucket
  filename: KC_Extract_1_20171009.csv

ADDR:
  mongodb_config:
    database: customer
    collection: address

s3_conf:
  s3_bucket: aws-rdd-bucket
  staging_dir: staging

REGIS_DIM:
  tableName: "DATAMART.REGIS_DIM"
  source_data:
    - CP
    - ADDR
  loadingQuery: >
              SELECT
              FN_UUID() AS REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID,REGIS_CTY_CODE AS CTY_CODE,
              REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_DT
              FROM
              (SELECT
              DISTINCT a.REGIS_CNSM_ID, CAST(a.REGIS_CTY_CODE AS SMALLINT), CAST(a.REGIS_ID AS INTEGER),
              a.REGIS_LTY_ID, a.REGIS_DATE, a.REGIS_CHANNEL, a.REGIS_GENDER, a.REGIS_CITY, b.state,b.city,b.street,
              a.INS_DT
              FROM
              CP a join ADDR b
                on a.REGIS_CNSM_ID=b.consumer_id
              WHERE
              a.INS_DT = '2022-01-15') CP


CHILD_DIM:
  tableName: "DATAMART.CHILD_DIM"
  source_data:
     - CP
  loadingQuery: >
          SELECT
          FN_UUID() AS CHILD_KEY, REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB,
          CHILD_GENDER, INS_DT
          FROM
          (SELECT DISTINCT REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, INS_DT
          FROM
          CP
          WHERE
          INS_DT = '2022-01-15' AND CHILD_ID IS NOT NULL) CP


redshift_conf:
  filetype: csv
  delimiter: |
